- name: Setup the App
  hosts: all
  become: yes
  vars:
    app_targets:
      - "192.168.1.102"
  tasks:
  - import_tasks: ./install_prometheus.yml
    vars:
      prometheus_user: prometheus
      prometheus_url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
      prometheus_download_dir: prometheus-2.52.0.linux-amd64
      prometheus_executable: prometheus

  - import_tasks: ./install_grafana.yml
