{
 "title": "My App",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[30d]) + avg_over_time(node_memory_Cached_bytes[30d]) + avg_over_time(node_memory_Buffers_bytes[30d])) / avg_over_time(node_memory_MemTotal_bytes[30d])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(le) (delta(axum_http_requests_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status) (delta(axum_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}