- name: Pull the App Image
  community.docker.docker_image:
    name: "{{ app_image }}"
    source: pull
- name: Create default containers
  community.docker.docker_container:
    name: "{{ app_container }}"
    image: "{{ app_image }}"
    state: started
    auto_remove: yes
    env:
      DB_URI: "{{ db_uri }}"
      MIGRATE: "{{ migrate }}"
    ports:
      - "80:80"
      - "3000:3000"
