### Create Poll
POST http://localhost:8080/api/polls
Content-Type: application/json

{
  "title": "titulo",
  "options": ["first", "second"]
}

### Get Poll
GET http://localhost:8080/api/polls/3

### Get Poll Result
GET http://localhost:8080/api/polls/3/results

### Vote Poll
POST http://localhost:8080/api/polls/3
Content-Type: application/json

{
  "answer_id": 5
}

### End Poll
POST http://localhost:8080/api/polls/1/end
