### Create Poll
POST http://localhost:3000/api/polls
Content-Type: application/json

{
  "title": "titulo",
  "options": ["first", "second"]
}

### Get Poll
GET http://localhost:3000/api/polls/1

### Get Poll Result
GET http://localhost:3000/api/polls/1/results

### Vote Poll
POST http://localhost:3000/api/polls/1
Content-Type: application/json

{
  "answer_id": 2
}

### End Poll
POST http://localhost:3000/api/polls/1/end
